//! Autogenerated weights for `pallet_task_rewards`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-IGJFJ6F`, CPU: `AMD Ryzen 7 3700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::{
	deps::frame_support::{
		traits::Get,
		weights::{constants::RocksDbWeight, Weight},
	},
	prelude::*,
};

use core::marker::PhantomData;

/// Weight functions for `pallet_task_rewards`.
pub trait WeightInfo {
	fn create_task() -> Weight;
	fn submit_task() -> Weight;
	fn approve_submission() -> Weight;
	fn reject_submission() -> Weight;
	fn close_task() -> Weight;
}

/// Weights for `pallet_task_rewards`.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TaskRewards::NextTaskId` (r:1 w:1)
	/// Storage: `TaskRewards::Tasks` (r:0 w:1)
	fn create_task() -> Weight {
		Weight::from_parts(32_940_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `TaskRewards::Tasks` (r:1 w:0)
	/// Storage: `TaskRewards::Submissions` (r:1 w:1)
	fn submit_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `TaskRewards::Tasks` (r:1 w:0)
	/// Storage: `TaskRewards::Submissions` (r:1 w:1)
	/// Storage: `TaskRewards::Scores` (r:1 w:1)
	fn approve_submission() -> Weight {
		Weight::from_parts(38_430_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `TaskRewards::Tasks` (r:1 w:0)
	/// Storage: `TaskRewards::Submissions` (r:1 w:1)
	fn reject_submission() -> Weight {
		Weight::from_parts(29_880_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `TaskRewards::Tasks` (r:1 w:1)
	fn close_task() -> Weight {
		Weight::from_parts(34_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_task() -> Weight {
		Weight::from_parts(32_940_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn submit_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn approve_submission() -> Weight {
		Weight::from_parts(38_430_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn reject_submission() -> Weight {
		Weight::from_parts(29_880_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn close_task() -> Weight {
		Weight::from_parts(34_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}