//! Autogenerated weights for pallet_counter
//!
//! Temporary manually-written weights.
//! Replace this file with benchmark-generated weights before production.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_counter.
pub trait WeightInfo {
	fn increment() -> Weight;
	fn set_value() -> Weight;
	fn remove_counter() -> Weight;
}

/// Weights for pallet_counter using the Substrate node and recommended hardware.
#[cfg_attr(
	not(feature = "std"),
	deprecated(
		note = "SubstrateWeight is manually written and should be replaced with runtime benchmarked weights."
	)
)]
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage:
	/// - Counter Counters: read/write
	/// - System Account / Balances: may read/write when reserving deposit
	fn increment() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage:
	/// - Counter Counters: read/write
	/// - System Account / Balances: may read/write when reserving deposit
	fn set_value() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage:
	/// - Counter Counters: read/write
	/// - System Account / Balances: unreserve deposit
	fn remove_counter() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn increment() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn set_value() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn remove_counter() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}