//! Autogenerated-style weights for `pallet_tasks`
//!
//! NOTE: These are placeholder weights for the Phase 1 pilot.
//! Replace with benchmark-generated weights after benchmarking is added.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::{
	deps::frame_support::{
		traits::Get,
		weights::{constants::RocksDbWeight, Weight},
	},
	prelude::*,
};

use core::marker::PhantomData;

/// Weight functions for `pallet_tasks`.
pub trait WeightInfo {
	fn create_task() -> Weight;
	fn claim_task() -> Weight;
	fn submit_task() -> Weight;
	fn approve_task() -> Weight;
	fn reject_task() -> Weight;
	fn close_task() -> Weight;
	fn set_certificate_collection_id() -> Weight;
}

/// Weights for `pallet_tasks`.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Tasks::NextTaskId` (r:1 w:1)
	/// Storage: `Tasks::Tasks` (r:0 w:1)
	fn create_task() -> Weight {
		Weight::from_parts(32_940_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `Tasks::Tasks` (r:1 w:1)
	fn claim_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `Tasks::Tasks` (r:1 w:1)
	fn submit_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `Tasks::Tasks` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Storage: `Nfts::Account` (r:0 w:1)
	fn approve_task() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8000))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}

	/// Storage: `Tasks::Tasks` (r:1 w:1)
	fn reject_task() -> Weight {
		Weight::from_parts(29_880_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn close_task() -> Weight {
		Weight::from_parts(34_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}		

	fn set_certificate_collection_id() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_task() -> Weight {
		Weight::from_parts(32_940_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn claim_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn submit_task() -> Weight {
		Weight::from_parts(23_220_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn approve_task() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8000))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(6))
	}

	fn reject_task() -> Weight {
		Weight::from_parts(29_880_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn close_task() -> Weight {
		Weight::from_parts(34_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3542))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn set_certificate_collection_id() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
